### ISSUE TITLE
electron throw an exception "an object could not be cloned." when using number array

### ISSUE THREAD

**Issue by dollarzhaole** [Koromix/koffi#160]
I'm using electron 28 and koffi 2.8.0
the c code interface is 
`extern "C" 	EXPORT_API unsigned char*   foo(unsigned char* input, int length);`
and the ts code is
`const nativeFoo = lib.func(
  'unsigned char* foo(unsigned char*,int)',
);`

the code call this foo function is 
`  ipcMain.on('ipc-foo', (ev, args) => {
    console.log('args:', args);
    let data = [...args.input];
    ev.returnValue = nativeFoo(data, args.length);
  });`

when the 'ipc-foo' is handled, the app throws an exception, I guess from the deep c++ code or the koffi
![image](https://github.com/Koromix/koffi/assets/4970307/e9c691a9-2740-4f15-8fd7-5f9653480972)

please help me, it makes me crazy for seval days

**Comment by Koromix** [comment]
The `unsigned char *` return pointer is probably converted to an external object, and not a buffer, because Koffi does not know enough about the value to do it.

In your case, to answer, I need more info. Is the return value supposed to be a string? A binary buffer of size `length`? Or any other size (and how to know the expected length if that's the case)?
