### ISSUE TITLE
Compile error when building koffi on Windows

### ISSUE THREAD

**Issue by hatsuroku** [Koromix/koffi#167]
![image](https://github.com/Koromix/rygel/assets/24711906/0be735c6-d4d8-487f-a4e0-9be2079db8c4)

![image](https://github.com/Koromix/rygel/assets/24711906/90c1e9b8-c838-4f41-9f59-7ffdbfd3b3e1)

Environment:
Visual Studio Version: 2022 Community
Node.js Version: v20.13.1

**Comment by Koromix** [comment]
This is caused by a bug in the MSVC compiler in Visual Studio 17.10, in the template parser.

I have added a work around, using [/Zc:twoPhase-](https://learn.microsoft.com/en-us/cpp/build/reference/zc-twophase?view=msvc-170) to use the old non-compliant template parser, and published Koffi 2.8.10 with this.
