### ISSUE TITLE
about webpack error

### ISSUE THREAD

**Issue by YongJiangLee** [Koromix/koffi#199]
![image](https://github.com/user-attachments/assets/093a28b8-1683-4931-be64-b8eb48eb0fc7)
node version 20.11.1, koffi version 2.9.1, how can I solve this error..thanks

**Comment by Koromix** [comment]
Not sure what you're trying to do, Koffi uses native code. For obvious reasons, Koffi is not made for browsers (you can't load system libraries from inside a browser) but for Node.js and Electron.

If you're using it the correct context (Node.js, Electron, whatever), please configure webpack to bundle the native code (koffi.node files) correctly.

I can't help you more, because I don't know anything about webpack and frankly don't ever want to. However, there is some information about packaging and bundling Koffi the documentation: https://koffi.dev/packaging

**Comment by Koromix** [comment]
There is some webpack stuff in the electron-forge example:

- https://koffi.dev/packaging#electron-forge
- https://github.com/Koromix/rygel/tree/master/src/koffi/examples/electron-forge
